#!/usr/bin/env python3

"CLI version of Countdown"

from os import system

try:
    from rich.console import Console
except:
    Console = None

from countdown import parser, process_events, Category, Event

_cli = parser.add_argument_group("CLI-specific")

_cli.add_argument(
    '--no-rich', action='store_true',
    help="Do not display color or styling.")
# TODO: support NO_COLOR
_cli.add_argument(
    '-e', '--edit', action='store_true',
    help="Open the file in $EDITOR.")

if __name__ == '__main__':
    # pre-process for CLI
    args = parser.parse_args()
    if args.no_rich:
        Console = None
    if args.edit:
        system(f'$EDITOR "{args.file}"')
    
    # display
    _print = print
    def print(*objects):
        if Console is None:
            _print(*objects)
        else:
            Console().print(*objects, highlight=False)
    
    def display(e: Event):
        if args.days_until:
            print(e.days_until())
        else:
            print(e)

    # process
    events = process_events(args)

    if isinstance(events, dict):
        events: dict[Category, list[Event]]
        for c, es in events.items():
            print(c)
            for e in es:
                display(e)

    if isinstance(events, list):
        for e in events:
            display(e)
